spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
originairports:
  shutdown: "SEA"
# Spring Actuator configuration
management:
  endpoints:
    health:
      show-details: "always"
    web:
      exposure:
        include: "*"
    security:
      enabled: false
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@